name: Deploy To Development

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Development Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEV_VPS_HOST }}
          username: ${{ secrets.DEV_VPS_USER }}
          key: ${{ secrets.DEV_VPS_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.DEV_VPS_PATH }}
            git pull origin dev
            docker compose exec app composer install --optimize-autoloader --no-interaction --prefer-dist
            docker compose exec app php artisan migrate --seed --force
            docker compose exec app php artisan optimize:clear
