name: Deploy To Production

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master

jobs:
  test:
    uses: ./.github/workflows/ci.yml

  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    if: needs.test.result == 'success'
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Production Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.VPS_PATH }}
            docker compose exec app php artisan down
            git pull origin master
            docker compose exec app composer install --no-dev --optimize-autoloader --no-interaction
            docker compose exec app php artisan migrate --force
            docker compose exec app php artisan optimize
            docker compose exec app php artisan up
